[package]
name = "terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { workspace = true }
file_system = { workspace = true }
virtual_file_system = { workspace = true }
executable = { workspace = true }
task = { workspace = true }
users = { workspace = true }
shared = { workspace = true }
time = { workspace = true }
synchronization = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
time = { workspace = true }
little_fs = { workspace = true }
command_line_shell = { workspace = true }
abi_definitions = { workspace = true }

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
