
[settings.name]
fr = "Réglages"
en = "Settings"
[error.graphics]
fr = "Erreur graphique: {}"
en = "Graphics error : {}"
[error.file_system]
fr = "Erreur du système de fichiers: {}"
en = "File system error: {}"
[error.virtual_file_system]
fr = "Erreur du système de fichiers virtuel: {}"
en = "Virtual file system error: {}"
[error.failed_to_create_object]
fr = "Échec de la création de l'objet"
en = "Failed to create object"
[error.failed_to_get_child_object]
fr = "Échec de l'obtention de l'objet enfant"
en = "Failed to get child object"
[error.failed_to_set_environment_variable]
fr = "Échec de la définition de la variable d'environnement: {}"
en = "Failed to set environment variable: {}"
[error.invalid_utf8_string]
fr = "Chaîne UTF-8 invalide : {}"
en = "Invalid UTF-8 string: {}"
[error.failed_to_set_task_user]
fr = "Échec de la définition de l'utilisateur de la tâche: {}"
en = "Failed to set task user: {}"
[error.failed_to_get_current_task_identifier]
fr = "Échec de l'obtention de l'identifiant de la tâche en cours: {}"
en = "Failed to get current task identifier: {}"
[error.failed_to_read_directory]
fr = "Échec de la lecture du répertoire: {}"
en = "Failed to read directory: {}"
[error.failed_to_open_standard_file]
fr = "Échec de l'ouverture du fichier standard: {}"
en = "Failed to open standard file: {}"
[error.null_character_in_string]
fr = "Caractère nul dans la chaîne: {}"
en = "Null character in string: {}"
[error.failed_to_create_ui_element]
fr = "Échec de la création de l'élément d'interface utilisateur"
en = "Failed to create UI element"
[error.authentication_failed]
fr = "Échec de l'authentification: {}"
en = "Authentication failed: {}"

[tabs.general.title]
fr = "Général"
en = "General"
[tabs.general.message]
fr = "Les réglages généraux seront implémentés ici."
en = "General settings will be implemented here."

[tabs.password.title]
fr = "Mot de passe"
en = "Password"
[tabs.password.content.current_password]
fr = "Mot de passe actuel"
en = "Current Password"
[tabs.password.content.new_password]
fr = "Nouveau mot de passe"
en = "New Password"
[tabs.password.content.confirm_password]
fr = "Confirmer le mot de passe"
en = "Confirm Password"
[tabs.password.content.change_password]
fr = "Changer le mot de passe"
en = "Change Password"
