[package]
name = "virtual_machine"
version = "0.1.0"
edition = "2024"

[dependencies]
wamr-rust-sdk = { git = "https://github.com/bytecodealliance/wamr-rust-sdk.git", features = [
  "multi-module",
] }

shared = { workspace = true }
memory = { workspace = true }
file_system = { workspace = true }
virtual_file_system = { workspace = true }
little_fs = { workspace = true }
task = { workspace = true }
time = { workspace = true }
abi_declarations = { workspace = true }
abi_context = { workspace = true }
synchronization = { workspace = true }

[dev-dependencies]
graphics = { workspace = true, features = ["rendering_xrgb8888"] }
abi_definitions = { workspace = true }
users = { workspace = true }
drivers = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
executable = { workspace = true, features = ["building"] }

[[test]]
name = "virtual_machine_test"
path = "tests/test.rs"

[[test]]
name = "virtual_machine_test_2"
path = "tests/test_2.rs"

[[test]]
name = "virtual_machine_test_3"
path = "tests/test_3.rs"
