[package]
name = "virtual_machine"
version = "0.1.0"
edition = "2024"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wamr-rust-sdk = { git = "https://github.com/bytecodealliance/wamr-rust-sdk.git", features = [
    "multi-module",
] }

shared = { version = "0.1.0", path = "../shared" }
memory = { version = "0.1.0", path = "../memory" }
file_system = { path = "../file_system" }
virtual_file_system = { path = "../virtual_file_system" }
little_fs = { path = "../little_fs" }
task = { version = "0.1.0", path = "../task" }
time = { version = "0.1.0", path = "../time" }
abi = { version = "0.1.0", path = "../abi" }
synchronization = { version = "0.1.0", path = "../synchronization" }

[dev-dependencies]
users = { path = "../users", version = "0.1.0" }
drivers = { path = "../drivers", version = "0.1.0" }
futures = { path = "../futures" }
log = { path = "../log" }
executable = { path = "../executable", features = ["building"] }

[[test]]
name = "virtual_machine_test"
path = "tests/test.rs"

[[test]]
name = "virtual_machine_test_2"
path = "tests/test_2.rs"
