use core::num::NonZeroI32;

pub type WasiResult = i32;

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    Toobig = 1,
    Access = 2,
    Addrinuse = 3,
    Addrnotavail = 4,
    Afnosupport = 5,
    Again = 6,
    Already = 7,
    Badf = 8,
    Badmsg = 9,
    Busy = 10,
    Canceled = 11,
    Child = 12,
    Connaborted = 13,
    Connrefused = 14,
    Connreset = 15,
    Deadlk = 16,
    Destaddrreq = 17,
    Dom = 18,
    Dquot = 19,
    Exist = 20,
    Fault = 21,
    Fbig = 22,
    Hostunreach = 23,
    Idrm = 24,
    Ilseq = 25,
    Inprogress = 26,
    Intr = 27,
    Inval = 28,
    Io = 29,
    Isconn = 30,
    Isdir = 31,
    Loop = 32,
    Mfile = 33,
    Mlink = 34,
    Msgsize = 35,
    Multihop = 36,
    Nametoolong = 37,
    Netdown = 38,
    Netreset = 39,
    Netunreach = 40,
    Nfile = 41,
    Nobufs = 42,
    Nodev = 43,
    Noent = 44,
    Noexec = 45,
    Nolck = 46,
    Nolink = 47,
    Nomem = 48,
    Nomsg = 49,
    Noprotoopt = 50,
    Nospc = 51,
    Nosys = 52,
    Notconn = 53,
    Notdir = 54,
    Notempty = 55,
    Notrecoverable = 56,
    Notsock = 57,
    Notsup = 58,
    Notty = 59,
    Nxio = 60,
    Overflow = 61,
    Ownerdead = 62,
    Perm = 63,
    Pipe = 64,
    Proto = 65,
    Protonosupport = 66,
    Prototype = 67,
    Range = 68,
    Rofs = 69,
    Spipe = 70,
    Srch = 71,
    Stale = 72,
    Timedout = 73,
    Txtbsy = 74,
    Xdev = 75,
    Notcapable = 76,
    Shutdown = 77,
    Memviolation = 78,
    Unknown = 79,
}

impl From<Error> for NonZeroI32 {
    fn from(error: Error) -> Self {
        NonZeroI32::new(error as i32).unwrap()
    }
}

pub fn vfs_error(err: xila::virtual_file_system::Error) -> Error {
    use xila::virtual_file_system::Error as Vfs;
    match err {
        Vfs::PermissionDenied => Error::Access,
        Vfs::NotADirectory => Error::Notdir,
        Vfs::InvalidPath => Error::Inval,
        Vfs::AlreadyExists => Error::Exist,
        Vfs::RessourceBusy => Error::Again,
        Vfs::TooManyOpenFiles => Error::Nfile,
        Vfs::InvalidIdentifier => Error::Badf,
        _ => Error::Io,
    }
}
