[package]
name = "graphical_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { workspace = true }
file_system = { workspace = true }
virtual_file_system = { workspace = true }
executable = { workspace = true }
task = { workspace = true }
users = { workspace = true }
shared = { workspace = true }
time = { workspace = true }
authentication = { workspace = true }
miniserde = "0.1"
futures = { workspace = true }
log = { workspace = true }

[dev-dependencies]
drivers = { workspace = true }
time = { workspace = true }
little_fs = { workspace = true }
abi_definitions = { workspace = true }

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
