[package]
name = "abi"
version = "0.1.0"
edition = "2024"

[dependencies]
virtual_file_system = { path = "../virtual_file_system" }
file_system = { path = "../file_system" }
task = { path = "../task" }
time = { path = "../time" }
memory = { path = "../memory" }
network = { path = "../network" }
synchronization = { version = "0.1.0", path = "../synchronization" }
futures = { version = "0.1.0", path = "../futures" }
log = { version = "0.1.0", path = "../log" }

[build-dependencies]
cbindgen = "0.29"
 
[dev-dependencies]
drivers = { path = "../drivers" }
little_fs = { path = "../little_fs" }
users = { path = "../users" }
