[package]
name = "command_line_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
file_system = { path = "../../../Modules/File_system" }
virtual_file_system = { path = "../../../Modules/Virtual_file_system" }
executable = { path = "../../../Modules/Executable" }
task = { path = "../../../Modules/Task" }
users = { path = "../../../Modules/Users" }
authentication = { path = "../../../Modules/Authentication" }
futures = { version = "0.1.0", path = "../../../Modules/Futures" }
log = { path = "../../../Modules/Log" }

[dev-dependencies]
drivers = { path = "../../../Modules/Drivers" }
time = { path = "../../../Modules/Time" }
little_fs = { path = "../../../Modules/LittleFS" }


[[test]]
name = "integration_test"
path = "Tests/integration_test.rs"
