[package]
name = "time"
version = "0.1.0"
edition = "2024"

[dependencies]
file_system = { workspace = true }
log = { workspace = true }
shared = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
log = { workspace = true }

[[test]]
name = "integration"
path = "Tests/integration.rs"
