use crate::{Key, lvgl};

#[derive(Debug, Clone)]
pub struct Event {
    pub code: EventKind,
    pub target: *mut lvgl::lv_obj_t,
    pub key: Option<Key>,
}

impl Event {
    pub fn new(code: EventKind, target: *mut lvgl::lv_obj_t, key: Option<Key>) -> Self {
        Self { code, target, key }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum EventKind {
    All = lvgl::lv_event_code_t_LV_EVENT_ALL as u16,
    Pressed = lvgl::lv_event_code_t_LV_EVENT_PRESSED as u16,
    Pressing = lvgl::lv_event_code_t_LV_EVENT_PRESSING as u16,
    PressLost = lvgl::lv_event_code_t_LV_EVENT_PRESS_LOST as u16,
    ShortClicked = lvgl::lv_event_code_t_LV_EVENT_SHORT_CLICKED as u16,
    SingleClicked = lvgl::lv_event_code_t_LV_EVENT_SINGLE_CLICKED as u16,
    DoubleClicked = lvgl::lv_event_code_t_LV_EVENT_DOUBLE_CLICKED as u16,
    TripleClicked = lvgl::lv_event_code_t_LV_EVENT_TRIPLE_CLICKED as u16,
    LongPressed = lvgl::lv_event_code_t_LV_EVENT_LONG_PRESSED as u16,
    LongPressedRepeat = lvgl::lv_event_code_t_LV_EVENT_LONG_PRESSED_REPEAT as u16,
    Clicked = lvgl::lv_event_code_t_LV_EVENT_CLICKED as u16,
    Released = lvgl::lv_event_code_t_LV_EVENT_RELEASED as u16,
    ScrollBegin = lvgl::lv_event_code_t_LV_EVENT_SCROLL_BEGIN as u16,
    ScrollThrowBegin = lvgl::lv_event_code_t_LV_EVENT_SCROLL_THROW_BEGIN as u16,
    ScrollEnd = lvgl::lv_event_code_t_LV_EVENT_SCROLL_END as u16,
    Scroll = lvgl::lv_event_code_t_LV_EVENT_SCROLL as u16,
    Gesture = lvgl::lv_event_code_t_LV_EVENT_GESTURE as u16,
    GestureUp = lvgl::lv_event_code_t_LV_EVENT_GESTURE_UP as u16,
    GestureDown = lvgl::lv_event_code_t_LV_EVENT_GESTURE_DOWN as u16,
    GestureLeft = lvgl::lv_event_code_t_LV_EVENT_GESTURE_LEFT as u16,
    GestureRight = lvgl::lv_event_code_t_LV_EVENT_GESTURE_RIGHT as u16,
    Key = lvgl::lv_event_code_t_LV_EVENT_KEY as u16,
    Rotary = lvgl::lv_event_code_t_LV_EVENT_ROTARY as u16,
    Focused = lvgl::lv_event_code_t_LV_EVENT_FOCUSED as u16,
    Defocused = lvgl::lv_event_code_t_LV_EVENT_DEFOCUSED as u16,
    Leave = lvgl::lv_event_code_t_LV_EVENT_LEAVE as u16,
    HitTest = lvgl::lv_event_code_t_LV_EVENT_HIT_TEST as u16,
    InputDeviceReset = lvgl::lv_event_code_t_LV_EVENT_INDEV_RESET as u16,
    HoverOver = lvgl::lv_event_code_t_LV_EVENT_HOVER_OVER as u16,
    HoverLeave = lvgl::lv_event_code_t_LV_EVENT_HOVER_LEAVE as u16,
    CoverCheck = lvgl::lv_event_code_t_LV_EVENT_COVER_CHECK as u16,
    RefreshExtDrawSize = lvgl::lv_event_code_t_LV_EVENT_REFR_EXT_DRAW_SIZE as u16,
    DrawMainBegin = lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN_BEGIN as u16,
    DrawMain = lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN as u16,
    DrawMainEnd = lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN_END as u16,
    DrawPostBegin = lvgl::lv_event_code_t_LV_EVENT_DRAW_POST_BEGIN as u16,
    DrawPost = lvgl::lv_event_code_t_LV_EVENT_DRAW_POST as u16,
    DrawPostEnd = lvgl::lv_event_code_t_LV_EVENT_DRAW_POST_END as u16,
    DrawTaskAdded = lvgl::lv_event_code_t_LV_EVENT_DRAW_TASK_ADDED as u16,
    ValueChanged = lvgl::lv_event_code_t_LV_EVENT_VALUE_CHANGED as u16,
    Insert = lvgl::lv_event_code_t_LV_EVENT_INSERT as u16,
    Refresh = lvgl::lv_event_code_t_LV_EVENT_REFRESH as u16,
    Ready = lvgl::lv_event_code_t_LV_EVENT_READY as u16,
    Cancel = lvgl::lv_event_code_t_LV_EVENT_CANCEL as u16,
    Create = lvgl::lv_event_code_t_LV_EVENT_CREATE as u16,
    Delete = lvgl::lv_event_code_t_LV_EVENT_DELETE as u16,
    ChildChanged = lvgl::lv_event_code_t_LV_EVENT_CHILD_CHANGED as u16,
    ChildCreated = lvgl::lv_event_code_t_LV_EVENT_CHILD_CREATED as u16,
    ChildDeleted = lvgl::lv_event_code_t_LV_EVENT_CHILD_DELETED as u16,
    ScreenUnloadStart = lvgl::lv_event_code_t_LV_EVENT_SCREEN_UNLOAD_START as u16,
    ScreenLoadStart = lvgl::lv_event_code_t_LV_EVENT_SCREEN_LOAD_START as u16,
    ScreenLoaded = lvgl::lv_event_code_t_LV_EVENT_SCREEN_LOADED as u16,
    ScreenUnloaded = lvgl::lv_event_code_t_LV_EVENT_SCREEN_UNLOADED as u16,
    SizeChanged = lvgl::lv_event_code_t_LV_EVENT_SIZE_CHANGED as u16,
    StyleChanged = lvgl::lv_event_code_t_LV_EVENT_STYLE_CHANGED as u16,
    LayoutChanged = lvgl::lv_event_code_t_LV_EVENT_LAYOUT_CHANGED as u16,
    GetSelfSize = lvgl::lv_event_code_t_LV_EVENT_GET_SELF_SIZE as u16,
    InvalidateArea = lvgl::lv_event_code_t_LV_EVENT_INVALIDATE_AREA as u16,
    ResolutionChanged = lvgl::lv_event_code_t_LV_EVENT_RESOLUTION_CHANGED as u16,
    ColorFormatChanged = lvgl::lv_event_code_t_LV_EVENT_COLOR_FORMAT_CHANGED as u16,
    RefreshRequest = lvgl::lv_event_code_t_LV_EVENT_REFR_REQUEST as u16,
    RefreshStart = lvgl::lv_event_code_t_LV_EVENT_REFR_START as u16,
    RefreshReady = lvgl::lv_event_code_t_LV_EVENT_REFR_READY as u16,
    RenderStart = lvgl::lv_event_code_t_LV_EVENT_RENDER_START as u16,
    RenderReady = lvgl::lv_event_code_t_LV_EVENT_RENDER_READY as u16,
    FlushStart = lvgl::lv_event_code_t_LV_EVENT_FLUSH_START as u16,
    FlushFinish = lvgl::lv_event_code_t_LV_EVENT_FLUSH_FINISH as u16,
    FlushWaitStart = lvgl::lv_event_code_t_LV_EVENT_FLUSH_WAIT_START as u16,
    FlushWaitFinish = lvgl::lv_event_code_t_LV_EVENT_FLUSH_WAIT_FINISH as u16,
    SyncStart = lvgl::lv_event_code_t_LV_EVENT_SYNC_START as u16,
    SyncFinish = lvgl::lv_event_code_t_LV_EVENT_SYNC_FINISH as u16,
    SyncWaitStart = lvgl::lv_event_code_t_LV_EVENT_SYNC_WAIT_START as u16,
    SyncWaitFinish = lvgl::lv_event_code_t_LV_EVENT_SYNC_WAIT_FINISH as u16,
    VerticalSynchronization = lvgl::lv_event_code_t_LV_EVENT_VSYNC as u16,
    VerticalSynchronizationRequest = lvgl::lv_event_code_t_LV_EVENT_VSYNC_REQUEST as u16,
    StateChanged = lvgl::lv_event_code_t_LV_EVENT_STATE_CHANGED as u16,
    Checked = lvgl::lv_event_code_t_LV_EVENT_CHECKED as u16,
    Unchecked = lvgl::lv_event_code_t_LV_EVENT_UNCHECKED as u16,
    UpdateLayoutCompleted = lvgl::lv_event_code_t_LV_EVENT_UPDATE_LAYOUT_COMPLETED as u16,
    Last = lvgl::lv_event_code_t_LV_EVENT_LAST as u16,
    Custom1 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 1,
    Custom2 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 2,
    CloseRequested = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 3,
    Custom4 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 4,
    Custom5 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 5,
    Custom6 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 6,
    Custom7 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 7,
    Custom8 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 8,
    Custom9 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 9,
    Custom10 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 10,
    Custom11 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 11,
    Custom12 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 12,
    Custom13 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 13,
    Custom14 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 14,
    Custom15 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 15,
    Custom16 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 16,
    Custom17 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 17,
    Custom18 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 18,
    Custom19 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 19,
    Custom20 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 20,
    Custom21 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 21,
    Custom22 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 22,
    Custom23 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 23,
    Custom24 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 24,
    Custom25 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 25,
    Custom26 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 26,
    Custom27 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 27,
    Custom28 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 28,
    Custom29 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 29,
    Custom30 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 30,
    Custom31 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 31,
    Custom32 = lvgl::lv_event_code_t_LV_EVENT_LAST as u16 + 32,
    Preprocess = 0x8000,
}

impl EventKind {
    pub const fn into_lvgl_code(self) -> lvgl::lv_event_code_t {
        self as lvgl::lv_event_code_t
    }

    pub const fn from_lvgl_code(code: lvgl::lv_event_code_t) -> Self {
        match code {
            lvgl::lv_event_code_t_LV_EVENT_ALL => Self::All,
            lvgl::lv_event_code_t_LV_EVENT_PRESSED => Self::Pressed,
            lvgl::lv_event_code_t_LV_EVENT_PRESSING => Self::Pressing,
            lvgl::lv_event_code_t_LV_EVENT_PRESS_LOST => Self::PressLost,
            lvgl::lv_event_code_t_LV_EVENT_SHORT_CLICKED => Self::ShortClicked,
            lvgl::lv_event_code_t_LV_EVENT_SINGLE_CLICKED => Self::SingleClicked,
            lvgl::lv_event_code_t_LV_EVENT_DOUBLE_CLICKED => Self::DoubleClicked,
            lvgl::lv_event_code_t_LV_EVENT_TRIPLE_CLICKED => Self::TripleClicked,
            lvgl::lv_event_code_t_LV_EVENT_LONG_PRESSED => Self::LongPressed,
            lvgl::lv_event_code_t_LV_EVENT_LONG_PRESSED_REPEAT => Self::LongPressedRepeat,
            lvgl::lv_event_code_t_LV_EVENT_CLICKED => Self::Clicked,
            lvgl::lv_event_code_t_LV_EVENT_RELEASED => Self::Released,
            lvgl::lv_event_code_t_LV_EVENT_SCROLL_BEGIN => Self::ScrollBegin,
            lvgl::lv_event_code_t_LV_EVENT_SCROLL_THROW_BEGIN => Self::ScrollThrowBegin,
            lvgl::lv_event_code_t_LV_EVENT_SCROLL_END => Self::ScrollEnd,
            lvgl::lv_event_code_t_LV_EVENT_SCROLL => Self::Scroll,
            lvgl::lv_event_code_t_LV_EVENT_GESTURE => Self::Gesture,
            lvgl::lv_event_code_t_LV_EVENT_GESTURE_UP => Self::GestureUp,
            lvgl::lv_event_code_t_LV_EVENT_GESTURE_DOWN => Self::GestureDown,
            lvgl::lv_event_code_t_LV_EVENT_GESTURE_LEFT => Self::GestureLeft,
            lvgl::lv_event_code_t_LV_EVENT_GESTURE_RIGHT => Self::GestureRight,
            lvgl::lv_event_code_t_LV_EVENT_KEY => Self::Key,
            lvgl::lv_event_code_t_LV_EVENT_ROTARY => Self::Rotary,
            lvgl::lv_event_code_t_LV_EVENT_FOCUSED => Self::Focused,
            lvgl::lv_event_code_t_LV_EVENT_DEFOCUSED => Self::Defocused,
            lvgl::lv_event_code_t_LV_EVENT_LEAVE => Self::Leave,
            lvgl::lv_event_code_t_LV_EVENT_HIT_TEST => Self::HitTest,
            lvgl::lv_event_code_t_LV_EVENT_INDEV_RESET => Self::InputDeviceReset,
            lvgl::lv_event_code_t_LV_EVENT_HOVER_OVER => Self::HoverOver,
            lvgl::lv_event_code_t_LV_EVENT_HOVER_LEAVE => Self::HoverLeave,
            lvgl::lv_event_code_t_LV_EVENT_COVER_CHECK => Self::CoverCheck,
            lvgl::lv_event_code_t_LV_EVENT_REFR_EXT_DRAW_SIZE => Self::RefreshExtDrawSize,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN_BEGIN => Self::DrawMainBegin,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN => Self::DrawMain,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_MAIN_END => Self::DrawMainEnd,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_POST_BEGIN => Self::DrawPostBegin,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_POST => Self::DrawPost,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_POST_END => Self::DrawPostEnd,
            lvgl::lv_event_code_t_LV_EVENT_DRAW_TASK_ADDED => Self::DrawTaskAdded,
            lvgl::lv_event_code_t_LV_EVENT_VALUE_CHANGED => Self::ValueChanged,
            lvgl::lv_event_code_t_LV_EVENT_INSERT => Self::Insert,
            lvgl::lv_event_code_t_LV_EVENT_REFRESH => Self::Refresh,
            lvgl::lv_event_code_t_LV_EVENT_READY => Self::Ready,
            lvgl::lv_event_code_t_LV_EVENT_CANCEL => Self::Cancel,
            lvgl::lv_event_code_t_LV_EVENT_STATE_CHANGED => Self::StateChanged,
            lvgl::lv_event_code_t_LV_EVENT_CHECKED => Self::Checked,
            lvgl::lv_event_code_t_LV_EVENT_UNCHECKED => Self::Unchecked,
            lvgl::lv_event_code_t_LV_EVENT_CREATE => Self::Create,
            lvgl::lv_event_code_t_LV_EVENT_DELETE => Self::Delete,
            lvgl::lv_event_code_t_LV_EVENT_CHILD_CHANGED => Self::ChildChanged,
            lvgl::lv_event_code_t_LV_EVENT_CHILD_CREATED => Self::ChildCreated,
            lvgl::lv_event_code_t_LV_EVENT_CHILD_DELETED => Self::ChildDeleted,
            lvgl::lv_event_code_t_LV_EVENT_SCREEN_UNLOAD_START => Self::ScreenUnloadStart,
            lvgl::lv_event_code_t_LV_EVENT_SCREEN_LOAD_START => Self::ScreenLoadStart,
            lvgl::lv_event_code_t_LV_EVENT_SCREEN_LOADED => Self::ScreenLoaded,
            lvgl::lv_event_code_t_LV_EVENT_SCREEN_UNLOADED => Self::ScreenUnloaded,
            lvgl::lv_event_code_t_LV_EVENT_SIZE_CHANGED => Self::SizeChanged,
            lvgl::lv_event_code_t_LV_EVENT_STYLE_CHANGED => Self::StyleChanged,
            lvgl::lv_event_code_t_LV_EVENT_LAYOUT_CHANGED => Self::LayoutChanged,
            lvgl::lv_event_code_t_LV_EVENT_GET_SELF_SIZE => Self::GetSelfSize,
            lvgl::lv_event_code_t_LV_EVENT_INVALIDATE_AREA => Self::InvalidateArea,
            lvgl::lv_event_code_t_LV_EVENT_RESOLUTION_CHANGED => Self::ResolutionChanged,
            lvgl::lv_event_code_t_LV_EVENT_COLOR_FORMAT_CHANGED => Self::ColorFormatChanged,
            lvgl::lv_event_code_t_LV_EVENT_REFR_REQUEST => Self::RefreshRequest,
            lvgl::lv_event_code_t_LV_EVENT_REFR_START => Self::RefreshStart,
            lvgl::lv_event_code_t_LV_EVENT_REFR_READY => Self::RefreshReady,
            lvgl::lv_event_code_t_LV_EVENT_RENDER_START => Self::RenderStart,
            lvgl::lv_event_code_t_LV_EVENT_RENDER_READY => Self::RenderReady,
            lvgl::lv_event_code_t_LV_EVENT_FLUSH_START => Self::FlushStart,
            lvgl::lv_event_code_t_LV_EVENT_FLUSH_FINISH => Self::FlushFinish,
            lvgl::lv_event_code_t_LV_EVENT_FLUSH_WAIT_START => Self::FlushWaitStart,
            lvgl::lv_event_code_t_LV_EVENT_FLUSH_WAIT_FINISH => Self::FlushWaitFinish,
            lvgl::lv_event_code_t_LV_EVENT_SYNC_START => Self::SyncStart,
            lvgl::lv_event_code_t_LV_EVENT_SYNC_FINISH => Self::SyncFinish,
            lvgl::lv_event_code_t_LV_EVENT_SYNC_WAIT_START => Self::SyncWaitStart,
            lvgl::lv_event_code_t_LV_EVENT_SYNC_WAIT_FINISH => Self::SyncWaitFinish,
            lvgl::lv_event_code_t_LV_EVENT_VSYNC => Self::VerticalSynchronization,
            lvgl::lv_event_code_t_LV_EVENT_VSYNC_REQUEST => Self::VerticalSynchronizationRequest,
            lvgl::lv_event_code_t_LV_EVENT_UPDATE_LAYOUT_COMPLETED => Self::UpdateLayoutCompleted,
            lvgl::lv_event_code_t_LV_EVENT_LAST => Self::Last,
            lvgl::lv_event_code_t_LV_EVENT_PREPROCESS => Self::Preprocess,
            80 => Self::Custom1,
            81 => Self::Custom2,
            82 => Self::CloseRequested,
            83 => Self::Custom4,
            84 => Self::Custom5,
            85 => Self::Custom6,
            86 => Self::Custom7,
            87 => Self::Custom8,
            88 => Self::Custom9,
            89 => Self::Custom10,
            90 => Self::Custom11,
            91 => Self::Custom12,
            92 => Self::Custom13,
            93 => Self::Custom14,
            94 => Self::Custom15,
            95 => Self::Custom16,
            96 => Self::Custom17,
            97 => Self::Custom18,
            98 => Self::Custom19,
            99 => Self::Custom20,
            100 => Self::Custom21,
            101 => Self::Custom22,
            102 => Self::Custom23,
            103 => Self::Custom24,
            104 => Self::Custom25,
            105 => Self::Custom26,
            106 => Self::Custom27,
            107 => Self::Custom28,
            108 => Self::Custom29,
            109 => Self::Custom30,
            110 => Self::Custom31,
            111 => Self::Custom32,
            _ => Self::Last,
        }
    }
}

impl From<EventKind> for lvgl::lv_event_code_t {
    fn from(code: EventKind) -> Self {
        code.into_lvgl_code()
    }
}

impl From<lvgl::lv_event_code_t> for EventKind {
    fn from(code: lvgl::lv_event_code_t) -> Self {
        EventKind::from_lvgl_code(code)
    }
}
