[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
task_macros = { path = "./task_macros" }
users = { workspace = true }
embassy-executor = { workspace = true, default-features = false }
embassy-futures = { workspace = true }
smol_str = { version = "0.3" }
synchronization = { workspace = true }
futures = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
embassy-time = { workspace = true, features = ["std"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
embassy-time = { workspace = true, features = ["wasm"] }

[features]
default = []
std = []

[dev-dependencies]
drivers_native = { workspace = true }
