[package]
name = "Task"
version = "0.1.0"
edition = "2021"

[dependencies]
Users = { path = "../Users" }
embassy-executor = { version = "0.7" }
embassy-time = { version = "0.4.0" }
embassy-futures = { version = "0.1.1" }
smol_str = { version = "0.3" }
embassy-sync = { version = "0.6.2" }