[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
users = { path = "../users" }
embassy-executor = { version = "0.7", features = [
    "arch-std",
    "executor-thread",
] }
embassy-time = { version = "0.4.0", features = ["std"] }
embassy-futures = { version = "0.1.1" }
smol_str = { version = "0.3" }
synchronization = { path = "../synchronization" }
task_macros = { path = "task_macros" }
futures = { version = "0.1.0", path = "../futures" }

[features]
default = []
std = []

[dev-dependencies]
drivers = { path = "../drivers" }
