[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
cstr_core = "0.2.6"
file_system = { workspace = true }
lvgl_rust_sys = { git = "https://github.com/Xila-Project/lvgl_rust_sys.git", default-features = false }
#lvgl_rust_sys = { workspace = true, default-features = false }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
time = { workspace = true }
shared = { workspace = true }
synchronization = { workspace = true }
log = { workspace = true }
abi_declarations = { workspace = true }

[dev-dependencies]
drivers = { workspace = true }
users = { workspace = true }
task = { workspace = true }
futures = { workspace = true }
abi_definitions = { workspace = true }

[features]
default = []
rendering_rgb565 = []
rendering_xrgb8888 = []

[[test]]
name = "graphics"
path = "tests/graphics.rs"
