[package]
name = "Graphics"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg( target_os = "espidf" )'.dependencies]
lvgl = { git = "https://github.com/lvgl/lv_binding_rust.git", default-features = false, features = [
    "embedded-graphics",
    "unsafe_no_autoinit",
] }
#lvgl-sys = { version = "0.6.2" }
embedded-graphics = "0.8.1"
Screen = { path = "../Screen" }

[target.'cfg( target_arch = "x86_64" )'.dependencies]
lvgl = { git = "https://github.com/lvgl/lv_binding_rust.git", features = [] }
embedded-graphics = "0.8.1"
Screen = { path = "../Screen" }
