[package]
name = "task_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { workspace = true, features = ["full", "visit"] }
quote = { workspace = true }
darling = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }

[lib]
proc-macro = true
