[package]
name = "Graphical_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
Graphics = { path = "../../../Graphics" }
File_system = { path = "../../../File_system" }
Virtual_file_system = { path = "../../../Virtual_file_system" }
Executable = { path = "../../../Executable" }
Task = { path = "../../../Task" }
Users = { path = "../../../Users" }
Shared = { path = "../../../Shared" }
Time = { path = "../../../Time" }
Authentication = { path = "../../../Authentication" }
miniserde = "0.1"
Command_line_shell = { path = "../Command_line" }

[dev-dependencies]
Drivers = { path = "../../../Drivers" }
Time = { path = "../../../Time" }
LittleFS = { path = "../../../LittleFS" }
Terminal = { path = "../../Terminal" }

[[test]]
name = "Integration_test"
path = "Tests/Integration_test.rs"
