[project]
name = "reformat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lsp-types>=0.9.0",
    "pygls>=1.3.1",
    "python-lsp-jsonrpc>=1.1.2",
]
