[package]
name = "drivers"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.36"
log = { workspace = true }
file_system = { workspace = true }
virtual_file_system = { workspace = true }
task = { workspace = true }
users = { workspace = true }
graphics = { workspace = true }
time = { workspace = true }
shared = { workspace = true }
peripherals = { workspace = true }
network = { workspace = true }
memory = { workspace = true }
synchronization = { workspace = true }
linked_list_allocator = { version = "0.10", default-features = false, features = [
  "const_mut_refs",
] }

embassy-sync = { workspace = true }
futures = { workspace = true }
embassy-executor = { workspace = true }


[dev-dependencies]
little_fs = { workspace = true }


[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dev-dependencies]
#graphics = { workspace = true, features = ["RGB565"] }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
critical-section = { workspace = true, features = ["std"] }
pixels = "0.14"
winit = { version = "0.30", features = ["rwh_05"] }
rand = "0.9.0"
libc = { version = "0.2" }
getrandom = { version = "0.3.3" }
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-std",
  "executor-thread",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
critical-section = { workspace = true, features = ["std"] }
console_error_panic_hook = "0.1"
console_log = "1"
wasm-bindgen-futures = "0.4"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-wasm",
  "executor-thread",
] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3.64", features = [
  "Window",
  "Document",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "MouseEvent",
  "KeyboardEvent",
  "EventTarget",
  "ImageData",
  "Element",
  "HtmlElement",
  "DomRect",
  "console",
  # OPFS features
  "StorageManager",
  "StorageEstimate",
  "FileSystemDirectoryHandle",
  "FileSystemFileHandle",
  "FileSystemHandle",
  "FileSystemWritableFileStream",
  "WritableStream",
  "ReadableStream",
  "File",
  "Blob",
  "Navigator",
  "FileSystemGetFileOptions",
  "FileSystemCreateWritableOptions",
  "FileSystemSyncAccessHandle",
  "FileSystemReadWriteOptions",
  "WebGl2RenderingContext",
] }
js-sys = "0.3"


#[[te0.9.0.0]
#name = "native_graphics"
#path = "Tests/Native/graphics.rs"
