[package]
name = "File_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
Graphics = { path = "../../Graphics" }
File_system = { path = "../../File_system" }
Virtual_file_system = { path = "../../Virtual_file_system" }
Executable = { path = "../../Executable" }
Task = { path = "../../Task" }
Users = { path = "../../Users" }
Shared = { path = "../../Shared" }
Time = { path = "../../Time" }
Synchronization = { version = "0.1.0", path = "../../Synchronization" }
Futures = { version = "0.1.0", path = "../../Futures" }

[dev-dependencies]
Drivers = { path = "../../Drivers" }
Time = { path = "../../Time" }
LittleFS = { path = "../../LittleFS" }
Command_line_shell = { path = "../Shell/Command_line" }
