[package]
name = "users"
version = "0.1.0"
edition = "2024"

[dependencies]
synchronization = { workspace = true }

[dev-dependencies]
drivers = { workspace = true }
futures = { workspace = true }
task = { workspace = true }
