[package]
name = "users"
version = "0.1.0"
edition = "2024"

[dependencies]
synchronization = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
futures = { workspace = true }
task = { workspace = true }
