[package]
name = "Users"
version = "0.1.0"
edition = "2021"

[dependencies]
Synchronization = { version = "0.1.0", path = "../Synchronization" }

[dev-dependencies]
Futures = { path = "../Futures" }
Task = { path = "../Task" }
