[package]
name = "wasm_bindings"
version = "0.1.0"
edition = "2024"
build = "build/main.rs"

[features]
default = []
c_bindings = []

[build-dependencies]
lvgl_rust_sys = { git = "https://github.com/Xila-Project/lvgl_rust_sys.git", default-features = false }
bindgen = { workspace = true }
bindings_utilities = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "visit", "extra-traits"] }
target = { workspace = true }
proc-macro2 = { workspace = true }
cbindgen = { workspace = true }
