[error.graphics]
fr = "Graphique: {}"
en = "Graphics: {}"

[error.failed_to_create_object]
fr = "Échec de la création de l'objet"
en = "Failed to create object"

[error.utf8]
fr = "UTF-8: {}"
en = "UTF-8: {}"

[error.failed_to_mount_device]
fr = "Échec du montage du périphérique: {}"
en = "Failed to mount device: {}"

[error.failed_to_get_task_identifier]
fr = "Échec de la récupération de l'identifiant de la tâche: {}"
en = "Failed to get task identifier: {}"

[error.failed_to_execute]
fr = "Échec de l'exécution: {}"
en = "Failed to execute: {}"
