[package]
name = "little_fs"
version = "0.1.0"
edition = "2024"

[features]
std = ["file_system/std"]
default = []

[dependencies]
file_system = { path = "../file_system" }
task = { path = "../task" }
users = { path = "../users" }
time = { path = "../time" }
littlefs2-sys = { path = "../../../littlefs2-sys" }
synchronization = { version = "0.1.0", path = "../synchronization" }
futures = { path = "../futures" }

[dev-dependencies]
drivers = { path = "../drivers" }
futures = { path = "../futures" }
