[package]
name = "little_fs"
version = "0.1.0"
edition = "2024"

[features]
std = ["file_system/std"]
default = []

[dependencies]
file_system = { workspace = true }
task = { workspace = true }
users = { workspace = true }
time = { workspace = true }
littlefs2-sys = "0.3.1"
synchronization = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }
futures = { workspace = true }
