
#include "wasm.generated.h"

#define CLOCK_REALTIME XilaTimeClockIdentifier_Realtime
#define CLOCK_MONOTONIC XilaTimeClockIdentifier_Monotonic

#define TIMER_ABSTIME XilaTimerFlags_Absolute

typedef XilaConditionVariableAttribute pthread_condattr_t;

#define pthread_cond_init xila_condition_variable_initialize
#define pthread_condattr_init xila_condition_variable_attribute_initialize
#define pthread_condattr_setclock xila_condition_variable_attribute_set_clock
#define pthread_condattr_destroy xila_condition_variable_attribute_destroy

#define clock_nanosleep __wasm_task_sleep

#define sched_yield __wasm_task_yield