[package]
name = "settings"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { path = "../../modules/graphics" }
file_system = { path = "../../modules/file_system" }
virtual_file_system = { path = "../../modules/virtual_file_system" }
executable = { path = "../../modules/executable" }
task = { path = "../../modules/task" }
users = { path = "../../modules/users" }
shared = { path = "../../modules/shared" }
time = { path = "../../modules/time" }
synchronization = { version = "0.1.0", path = "../../modules/synchronization" }
futures = { version = "0.1.0", path = "../../modules/futures" }
log = { version = "0.1.0", path = "../../modules/log" }
authentication = { path = "../../modules/authentication" }

[dev-dependencies]
drivers = { path = "../../modules/drivers" }
little_fs = { path = "../../modules/little_fs" }
command_line_shell = { path = "../shell/command_line" }
abi_definitions = { workspace = true }

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
