[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
task = { path = "../task" }
users = { path = "../users" }
shared = { path = "../shared" }
synchronization = { version = "0.1.0", path = "../synchronization" }
futures = { version = "0.1.0", path = "../futures" }

[dev-dependencies]
drivers = { path = "../drivers" }

[features]
std = []
default = []
