[package]
name = "File_system"
version = "0.1.0"
edition = "2021"

[dependencies]
Task = { path = "../Task" }
Users = { path = "../Users" }
Shared = { path = "../Shared" }

[dev-dependencies]
Drivers = { path = "../Drivers" }

[features]
std = []
default = ["std"]
