[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
task = { workspace = true }
users = { workspace = true }
shared = { workspace = true }
synchronization = { workspace = true }
futures = { workspace = true }
embedded-io-async = { workspace = true }

[dev-dependencies]
drivers_native = { workspace = true }
drivers_core = { workspace = true }
drivers_shared = { workspace = true }
drivers_std = { workspace = true }

[features]
std = []
default = []
