[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
task = { workspace = true }
users = { workspace = true }
shared = { workspace = true }
synchronization = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
drivers = { workspace = true }

[features]
std = []
default = []
