[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
file_system = { path = "../File_system" }
futures = { version = "0.1.0", path = "../Futures" }
synchronization = { version = "0.1.0", path = "../Synchronization" }
time = { path = "../Time" }
