[package]
name = "bindings_utilities"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { workspace = true, features = ["full", "visit", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
