[package]
name = "WASM"
version = "0.1.0"
edition = "2021"
build = "Build.rs"

[dependencies]
File_system = { path = "../../File_system" }
Virtual_file_system = { path = "../../Virtual_file_system" }
Executable = { path = "../../Executable" }
Task = { path = "../../Task" }
Users = { path = "../../Users" }
Virtual_machine = { path = "../../Virtual_machine" }

[dev-dependencies]
Drivers = { path = "../../Drivers" }
Time = { path = "../../Time" }
LittleFS = { path = "../../LittleFS" }
Command_line_shell = { path = "../Shell/Command_line" }

[[test]]
name = "Integration_test"
path = "Tests/Integration_test.rs"
