use std::{env, path::PathBuf};

fn main() {
    // Tell Cargo to rerun this build script if any Rust source files change

    // Tell Cargo to rerun this build script if any Rust source files change
    println!("cargo:rerun-if-changed=src/");

    println!("cargo:warning=Generating bindings for ABI definitions...");

    let definitions_path: PathBuf = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is not set")
        .into();

    let header_file = "./wamr/include/wasm.generated.h".to_string();

    let enumeration_configuration = cbindgen::EnumConfig {
        prefix_with_name: true,
        ..Default::default()
    };

    const AFTER_INCLUDES: &str = "
#if defined(__GNUC__) || defined(__clang__)
#  define ALIGNED(n) __attribute__((aligned(n)))
#elif defined(_MSC_VER)
#  define ALIGNED(n) __declspec(align(n))
#else
#  define ALIGNED(n)
#endif
";

    let configuration: cbindgen::Config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("__WASM_GENERATED_H_INCLUDED".to_string()),
        include_version: true,
        after_includes: Some(AFTER_INCLUDES.to_string()),
        autogen_warning: Some(
            "/* This file is automatically generated by cbindgen. Do not edit it manually. */"
                .to_string(),
        ),
        sys_includes: vec![
            "stdarg.h".to_string(),
            "stdbool.h".to_string(),
            "stdint.h".to_string(),
        ],
        includes: vec!["../../../../../modules/abi/xila.h".to_string()],
        no_includes: true,
        enumeration: enumeration_configuration,
        export: cbindgen::ExportConfig {
            exclude: vec!["XilaTaskIdentifier".to_string()],
            ..Default::default()
        },
        parse: cbindgen::ParseConfig {
            expand: cbindgen::ParseExpandConfig {
                crates: vec!["wasm_abi_bindings".to_string()],
                features: Some(vec!["wasm_abi_bindings/bindings_generation".to_string()]),
                ..Default::default()
            },
            ..Default::default()
        },
        layout: cbindgen::LayoutConfig {
            aligned_n: Some("ALIGNED".to_string()),
            ..Default::default()
        },
        ..Default::default()
    };

    // temporarly enable nightly for macro expansion

    unsafe {
        env::set_var("RUSTC_BOOTSTRAP", "1");
    }

    cbindgen::Builder::new()
        .with_crate(definitions_path)
        .with_config(configuration)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&header_file);
}
