[error.authentication_failed]
fr = "Échec de l'authentification: {}"
en = "Authentication failed: {}"
[error.failed_to_set_task_user]
fr = "Échec de la définition de l'utilisateur de la tâche: {}"
en = "Failed to set task user: {}"
[error.failed_to_set_environment_variable]
fr = "Échec de la définition de la variable d'environnement: {}"
en = "Failed to set environment variable: {}"
[error.failed_to_tokenize_command_line]
fr = "Échec de la tokenisation de la ligne de commande"
en = "Failed to tokenize command line"
[error.missing_file_name_after_redirect_out]
fr = "Nom de fichier manquant après la redirection de sortie"
en = "Missing file name after redirect out"
[error.missing_file_name_after_redirect_in]
fr = "Nom de fichier manquant après la redirection d'entrée"
en = "Missing file name after redirect in"
[error.missing_command]
fr = "Commande manquante"
en = "Missing command"
[error.command_not_found]
fr = "Commande introuvable"
en = "Command not found"
[error.failed_to_get_task_identifier]
fr = "Échec de la récupération de l'identifiant de la tâche"
en = "Failed to get task identifier"
[error.invalid_path]
fr = "Chemin invalide"
en = "Invalid path"
[error.failed_to_get_path]
fr = "Échec de la récupération de la variable d'environnement"
en = "Failed to get environment variable"
[error.failed_to_execute_command]
fr = "Échec de l'exécution de la commande"
en = "Failed to execute command"
[error.failed_to_join_task]
fr = "Échec de la jonction de la tâche"
en = "Failed to join task"
[error.invalid_number_of_arguments]
fr = "Nombre d'arguments invalide"
en = "Invalid number of arguments"
