name: Build and deploy rust documentation to Github Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v4

      - name: Setup | Enable cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "Documentation"

      - name: Setup | Install GCC multilib
        run: sudo apt update && sudo apt install -y gcc-multilib clang-format

      - name: Setup | Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, wasm32-wasip1

      - name: Setup | Cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Setup | Trunk
        run: cargo binstall trunk --no-confirm

      - name: Build | Documentation
        run: |
          cargo doc --all-features
          cp ./documentation/index.html ./target/doc

      - name: Build | WASM demonstration
        working-directory: ./examples/wasm
        run: |
          trunk build --release
          cp -r ./dist/* ../../target/doc/demonstrations/wasm/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
