name: Continuous integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  rust-checks:
    name: Rust checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          - esp32
          - esp32s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.target }}"

      - name: Setup stable rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Setup ESP rust toolchain
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32,esp32s3
          ldproxy: true
        
      - name: Install necessary dependencies
        run: sudo apt-get install -y libsdl2-dev

      - name: Build and enable build tool
        run: source Export.sh

      - name: Check formatting
        run: Build_tool/target/release/Build_tool format --all -- --check --color always

      - name: Check clippy
        run: Build_tool/target/release/Build_tool clippy ${{ matrix.target }} --all-features --workspace -- -D warnings

      - name: Run tests
        run: Build_tool/target/release/Build_tool test ${{ matrix.target }} --all -- --include-ignored
